capstan_arm_position_controller:
  type: effort_controllers/JointPositionController
  joint: capstan_arm
  pid: {p: 60.0, i: 0.0, d: 1.0}

base_arm_rot_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_arm_rot
  pid: {p: 60.0, i: 0.0, d: 1.0}

arm_elbow_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_elbow
  pid: {p: 50.0, i: 0.0, d: 1.0}

arm_elbow_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_elbow_roll
  pid: {p: 30.0, i: 0.0, d: 0.5}